// Generated by Oryn.Generator 1.0.8.
// This file is the user-facing generated source stub. Runqemu.sh composes Templates/Kernel.template.cs before compiling.
// OS: DES
// Kernel: DESKernel

public static class Kernel
{
    public static void Main()
    {
    }
}
