// Generated by Oryn.Generator 1.0.6.
// This file is the user-facing generated source stub. Runqemu.sh composes Templates/Kernel.template.cs before compiling.
// OS: DSOOS
// Kernel: DSOOSKernel

public static class Kernel
{
    public static void Main()
    {
    }
}
