// Generated by Oryn.Generator 1.0.4.
// This file is the user-facing generated source stub. Runqemu.sh composes Templates/Kernel.template.cs before compiling.
// OS: Dsos
// Kernel: DsosKernel

public static class Kernel
{
    public static void Main()
    {
    }
}
