// Generated by Oryn.Generator 1.0.3.
// This file is the user-facing generated source stub. Runqemu.sh composes Templates/Kernel.template.cs before compiling.
// OS: DSOS
// Kernel: DSOSKernel

public static class Kernel
{
    public static void Main()
    {
    }
}
